include:
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'build-image.template.yaml'
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'helm.template.yaml'

default:
  tags:
    - adcorn-dev

variables:
  APP_NAME: "app"
  APP_NAMESPACE: "${CI_PROJECT_ROOT_NAMESPACE}-${CI_PROJECT_NAME}"
  ENVIRONMENT: dev
  KUBECONFIG_B64: $DEV_KUBECONFIG_B64

stages:
  - build
  - deploy

build:
  stage: build
  extends: .build_image
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        BUILD_ARGS: "--build-arg NODE_ENV=development"
    - if: $CI_COMMIT_REF_NAME == "release"
      variables:
        BUILD_ARGS: "--build-arg NODE_ENV=production"
        ENVIRONMENT: prod
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH'

deploy:
  extends: .helm_upgrade
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        CONFIG: $DEV_CONFIG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "release"'
      variables:
        KUBECONFIG_B64: $PROD_KUBECONFIG_B64
        ENVIRONMENT: prod
    - if: '$CI_COMMIT_REF_NAME == "master"'

