include:
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'build-image.template.yaml'
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'helm.template.yaml'

default:
  tags:
    - adcorn-dev

variables:
  APP_NAME: "stats"
  APP_NAMESPACE: "${CI_PROJECT_ROOT_NAMESPACE}-${CI_PROJECT_NAME}"
  ENVIRONMENT: dev

stages:
  - build
  - deploy

build:
  stage: build
  extends: .build_image
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        BUILD_ARGS: "--build-arg NODE_ENV=development --build-arg TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN} --build-arg FETCH_RSS_COM_TOKEN=${FETCH_RSS_COM_TOKEN}"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH'

deploy:
  extends: .helm_upgrade
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "release"'
