apiVersion: v1
kind: ConfigMap
metadata:
  name: config-secrets
  labels:
    timestamp: {{ .Values.timestamp | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "53"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  .env: {{ .Values.config }}
