name: Mirror and run GitLab CI

on: [push]

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://adcorn-prod.gitlab.yandexcloud.net/defihelper/stats"
      env:
        GITLAB_HOSTNAME: "adcorn-prod.gitlab.yandexcloud.net"
        GITLAB_USERNAME: "vkomissarov"
        GITLAB_PASSWORD: "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"
        GITLAB_PROJECT_ID: "12"
        GITHUB_TOKEN: ${{ secrets.GTHUB_TOKEN }}
